### PR TITLE
Added Windows style folder union

### PR DESCRIPTION
**Pull request by EmmanuelMess**
```
t/                                 t/                            t/
|-- b                              |-- n                         |-- b
|-- k/                             |-- k/                        |-- n
|   |-- c                          |   |-- c                     |-- k/
|-- j/                             |-- j/                        |   |-- c
|   |-- d           +              |   |-- l           =         |-- j/
                                   |-- h/                        |   |-- d
                                   |   |-- m                     |   |-- l
                                   |   |-- r/                    |-- h/
                                   |   |   |-- z                 |   |-- m
                                                                 |   |-- r/ 
                                                                 |   |   |-- z
```
Plus a conflict with t/k/c. Also reformatted and renamed a bit the code. If you find error I will try to solve them as soon as possible. Also if you wouldn't like this feature added by default, at least let me add a setting to activate it. Thank you for your patience.

### CODE REVIEW

**Comment by vishal0071** [comment]
@EmmanuelMess I checked the default behaviour of Amaze, it already does pretty much the same thing if you press on overwrite option in confirmation dialog. Please explain a use case as I failed to get your point.

**Comment by EmmanuelMess** [comment]
Ok, I thought overwrite deleted the "overwriten" folder (oops). Just one thing, The conflict with c doesn't show on my phone, is it just me?

**Comment by vishal0071** [comment]
Conflict​ with c?

**Comment by EmmanuelMess** [comment]
With file 'c' under folder k

**Comment by vishal0071** [comment]
What's the conflict with it? It's overwritten, as expected.

**Comment by EmmanuelMess** [comment]
Well, my code doesn't overwrite folders, just files, showing a dialogue for
each collision,

**Comment by vishal0071** [comment]
And selecting 'Do for all items' works like it's supposed to, with this behavior?

**Comment by EmmanuelMess** [comment]
Yes

**Comment by vishal0071** [comment]
Great! Thanks for your contribution, I'll merge it.
Can you please make changes to play's MainActivity instead of fdroid, as it's out of date and I will overwrite all changes made to it.

**Comment by EmmanuelMess** [comment]
Will do ASAP.

**Comment by EmmanuelMess** [comment]
Should be working

**Comment by vishal0071** [comment]
Great! Thanks (:

**Pull request merged**
