### PR TITLE
ci: enable cache of set java

### LINKED ISSUE #2586: Faster testing/CI
**Describe the bug**
Reduce time for tests on CI. We have 2000 min/month available, it would be a good idea to reduce the time tests takes to run as each run takes ~30min.

Any ideas are welcome.

### PR DESCRIPTION
**Pull request by Bambooin**
## Description
Enable gradle cache to speed up time of ci.

#### Issue tracker   

Fixes #2586 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [X] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [X] `./gradlew assembledebug`
- [X] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
Just caching the `spotlessCheck` and not the actual build task?

**Comment by VishalNehra** [comment]
Also point this fix to #2586

**Comment by VishalNehra** [comment]
There's. a build failure. Can you check? It's a new class created I recently  pushed some changes in release/3.7
Maybe rebase your branch once?

**Comment by Bambooin** [comment]
I will rebase to tigger ci.

**Comment by Bambooin** [comment]
It fails on last commit:  663bf4dcbd4b3eb1ff9ab749529089ffe62eb774

https://github.com/TeamAmaze/AmazeFileManager/runs/3914037467

Root failure reason: 
```
e: /home/runner/work/AmazeFileManager/AmazeFileManager/app/src/main/java/com/amaze/filemanager/ui/selection/SelectionPopupMenu.kt: (56, 43): Unresolved reference: simpleTheme
```

**Comment by VishalNehra** [comment]
Checking

**Pull request merged**
