### PR TITLE
Helping branch

### PR DESCRIPTION
**Pull request by santaasus**
Fix todo and some issues

### CODE REVIEW

**Comment by vishal0071** [comment]
Thanks for the contribution. Let me test this first before merging.

**Comment by vishal0071** [comment]
Request you to make switch to playDebug build variant and change code in it's MainActivity instead of fdroidDebug. This is so because changes made to fdroidDebug's MainActivity are overwritten during every build. So your code will come to fdroid version, but it needs to be passed to play version first.

**Comment by santaasus** [comment]
Changed play module with MainActivity, but in fdroid MainActivity i found some errors like this :menu_item2, item10, MainActivity.TAG_INTENT_FILTER_FAILED_OPS.

**Comment by vishal0071** [comment]
Like I said, fdroid MainActivity is not up to date and all changes in it will be overwritten by play's. That's why I'm telling you to make changes on play's one.

**Comment by santaasus** [comment]
I switched to master branch and saw in MainActivity's class field MainFragment , but when I'm starting project there is not overwritten field Main to MainFragment in fdroid. Where Is i wrong ?

**Comment by vishal0071** [comment]
Like I said, fdroid is outdated. There is no Main now, it's been renamed to MainFragment on play version. It'll be soon merged on fdroid too.

**Comment by santaasus** [comment]
Well I updated play's MainActivity ?

**Comment by vishal0071** [comment]
Great! Then commit the changes and they will be added in this PR.

**Comment by vishal0071** [comment]
Good to see that you merged with master. But like I said, I won't be able to test and accept these changes unless you make them in play/MainActivity. Any and all changes to fDroid/MainActivity will be overwritten.

**Comment by santaasus** [comment]
I should put my changes to play -> MainActivity, right ? If it's true, I have did this already.Maybe we're talking about different things ? 😄

**Comment by vishal0071** [comment]
The summary of changes shows you made changes to three files - fdroid/MainActivity, TabFragment, AppConfig
Please look into it.

**Comment by santaasus** [comment]
You're right, I added in the play module changes, but there isn't any changes, it's very strange. Ok, I soon correct this file.

**Comment by rootbyos** [comment]
can't found MainActivity in package  activities folder, there are some problems when i build this project

**Pull request closed without merging**
