### PR TITLE
a tiny addition to customize the toast on opening

### PR DESCRIPTION
**Pull request by moovida**
This very small change would allow external apps to send a message to the user on opening of amaze. 

This could be seen as a file selection window title, done the very easy way.

### CODE REVIEW

**Comment by vishal0071** [comment]
You forgot to assign value to title from the if case.

**Comment by moovida** [comment]
Outch, making an error in so few lines of code is really bad, sorry. Going to fix it at once :-/

**Comment by moovida** [comment]
Ok, fixed. Also extracted key to Constants to add some javadoc example, hope that is ok.

**Comment by vishal0071** [comment]
Great!

**Pull request merged**
