### PR TITLE
Force chooser on open-with, allow default handler for archives

### PR DESCRIPTION
**Pull request by lbdroid**
Long-click selection --> menu --> open with, should force chooser for file handler rather than opening the default handler, which will be automatically called on short-click.

### CODE REVIEW

**Comment by lbdroid** [comment]
The second commit in this pull request is to solve the issue of being able to maintain transition animations when launching internal archive file handlers, while still respecting system wide default file handlers for those files. It does so by querying the PackageManager to determine if (a) we ARE the default handler (handle internally), (b) there ARE NO handlers (handle internally), (c) there are multiple handlers (launch using openunknown, which will present an option to set default).

**Comment by arpitkh96** [comment]
I will review your code by today

**Comment by arpitkh96** [comment]
this didnt worked for me.it always opens new activity whatever is the case

**Comment by lbdroid** [comment]
I'm going to try to reproduce. What file type are you testing with? Do you have alternative handlers for that file type installed? What are they?

**Comment by arpitkh96** [comment]
Zip file... I tried both with and without other handlers

**Comment by arpitkh96** [comment]
also tried settings "always" in app chooser

**Comment by lbdroid** [comment]
Ah, I know what it is.
I just need a minute to fix it.

**Comment by lbdroid** [comment]
Sorry about that. I sent you another pull request with the fix.

**Pull request merged**
