### PR TITLE
update zh-tw translations

### PR DESCRIPTION
**Pull request by Brli**

### CODE REVIEW

**Comment by Brli** [comment]
how can I help to get play store having localized changelog?

**Comment by vishal0071** [comment]
Well, for that you need to send the translation to me privately. You have the text, you can translate and mail me. I'll update.

**Comment by Brli** [comment]
I don't know if I have the text :| do you mean this file https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/res/values/changelog.xml ?
btw, I can also do the overview part, will update you soon :)

**Comment by vishal0071** [comment]
You can get the english text from play store itself and send the translation to me. I'll update it.

**Pull request merged**
