### PR TITLE
Fix API changes after upgrading Google Play Billing library

### PR DESCRIPTION
**Pull request by TranceLove**
After passing #1863 almost all builds going into Travis CI had failed, with error messages pointing to usage of Google Play Billing library.

Sorry for overlooking... but patch for updated API usage is here.

Not sure where to start with testing... so @EmmanuelMess @VishalNehra please help testing it out.

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
I have no idea how to test/fix this.

**Comment by TranceLove** [comment]
As far as I can see (without playing with mocks/shadows in Robolectric) the easiest, pragmatic (yet disturbing and annoying) way to test the PR is to post a build to Google Play Console and let you test from there - the same way as I do in my daytime work.

@VishalNehra @EmmanuelMess I'll send you the details about testing.
(@bowiechen if you'd like to please PM me your gmail account privately, I'll add you to the tester list)

**Comment by VishalNehra** [comment]
I had done the implementation of this part so I will probably remember once I start testing. It's easy, no need to push a release to test.

**Review by bowiechen — APPROVED** [review]

**Comment by VishalNehra** [comment]
Tested, working fine. Note however this won't work on debug version as the app package need to be deployed on play store.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
