### PR TITLE
Changed how ThemedImageView works and solved black shortcut items on dark theme

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Changed how ThemedImageView works, not very fundamental, but now it sets a color filter that's white (#FFFFFFFF) instead of using another image, changed layouts accordingly, but left the old png's.
Also, now shortcut preferences have white icon when on dark theme.

### CODE REVIEW

**Comment by vishal0071** [comment]
This will lead to slow layout rendering. Loading a resource is always better than manually processing it.

**Comment by EmmanuelMess** [comment]
The thing is if android first converts vectors into bitmaps or first applies the color. I know your images are pngs, but the idea was to lay the grounds to start using vectors.

**Comment by vishal0071** [comment]
We're already using vectors for places where it is really required, for eg. themed icons in drawer. We can't theme every icon resource for every color. But the least we can do is provide a separate dark and light icons for places it's required.

**Comment by EmmanuelMess** [comment]
> But the least we can do is provide a separate dark and light icons for places it's required.

Why? Changing a vector's color is very inexpensive.

**Comment by vishal0071** [comment]
@EmmanuelMess then for light theme make them gray. You can pick the shade from existing icons.

**Comment by EmmanuelMess** [comment]
@vishal0071 For light theme they are black if clickable and grey if disabled. What are you proposing?

**Comment by vishal0071** [comment]
Black is not an option. Pick a shade of grey from normal icons. For disabled ones, a relatively lighter shade will do.

**Pull request merged**
