### PR TITLE
Format code with latest code style

### PR DESCRIPTION
**Pull request by Bambooin**
## Description
Format code with latest format tool.

### **The v2 patch doesn't change any code logic.**

I disable some ktlint standard rules in kotlin files:
```
[*.{kt,kts}]
ktlint_standard_no-wildcard-imports = disabled
ktlint_standard_property-naming = disabled
ktlint_standard_value-argument-comment = disabled
ktlint_standard_kdoc-wrapping = disabled
ktlint_standard_no-consecutive-comments = disabled
```

**For these rules, we can fix them in the future pull request one by one.**

Unit test is passed and was verified and tested with LineageOS 20.

The left Codacy issues were almost function too long, and this is can be fixed by update setting.

The last commit fix can be cherry pick to `release/3.10` branch.

For the pending pull requests:
- Apply code style in the branch
- Rebase the main branch

#### Automatic tests

- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- OS: LineageOS 20

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishnuSanal** [comment]
@Bambooin thanks a lot for the effort, but we have updated spotless (the library we use to enforce formatting) to the latest version without this humongous of a change (please see #3822). please check whether this would PR be a duplicate to that & LMK.

**Comment by Bambooin** [comment]
@VishnuSanal Sorry, I missed the #3822 which is very similar to this one.

This pull request only suppress one rule with `standard:max-line-length` in one file.

Other standard rules are enabled and fixed one by one manually.

Especially for the rule: `standard:no-wildcard-imports` this one should be enabled.

https://developer.android.com/kotlin/style-guide#import_statements
> Wildcard imports (of any type) are **not allowed**.

This rule needs to be fixed by hand one by one which spends lots of time and effort.

IMO, we should follow Kotlin code conventions, and disable rules with reasonable purpose.

Such as the regex expression in `NetCopyConnectionInfo.kt` should supressed, but other rules should be kept.

This pull request was created after a myriad of pull requests were merged recently to avoid conflicts.

**Comment by VishnuSanal** [comment]
@Bambooin i personally wouldn't vouch for a PR with ~350 file changes, since it breaks git history. I think the cost outweighs the benefits. this is why I created the other spotless PR before, it first gave me a whole lot of changes & (just like you did!) I had to try disabling individual rules manually to get to the current amount of files changed (~30 files). requesting for opinions from @VishalNehra @TranceLove & @EmmanuelMess here.

**Comment by Bambooin** [comment]
@VishnuSanal We can use git blame ignore file to skip this commit.

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

For this pull request with **too much** change is not my git way too, we should keep each commit clean and elegant.

**Comment by Bambooin** [comment]
All CI check and test passed except code static anylysis failed with too long function.

**Comment by VishalNehra** [comment]
Can you fix the static code analysis failure as well? Let me know if there's any rule that you would want to ignore for now, but we should be able to fix too long functions.

**Comment by Bambooin** [comment]
There are 9 functions are too lang which exceed maximum length 60.
https://github.com/TeamAmaze/AmazeFileManager/runs/18341863611

I tried and failed to refactor these too complex functions.

Such as this function is 199 lines with new code style.
> app/src/main/java/com/amaze/filemanager/utils/MainActivityActionMode.kt#L245
> The function onActionItemClicked is too long (199). The maximum length is 60.

**Comment by VishalNehra** [comment]
I was planning to merge it with the next release cycle after few days. There were always going to be merge conflicts here, so I'm trying to minimise them by making a release and then starting work on new release after merging this first.

**Comment by Bambooin** [comment]
Waiting for the new release and try to merge or rebaes(hard)...

**Comment by VishalNehra** [comment]
Hi, we just published a new release. Can you please rebase and we'll push this to merge. Sorry it took so long. 
While you're at it, can you please also update the licence year in template in license_amaze_strings as well.

**Comment by VishalNehra** [comment]
I'm not able to see your previous changes here now. Did you remove old commits?

**Comment by Bambooin** [comment]
@VishalNehra The v1 patch is very hard to **rebase and code review**, so I rewrite the v2 patch from scratch.

Sorry for the long waiting time, it's ready to code review right now.

> While you're at it, can you please also update the licence year in template in license_amaze_strings as well.

Does this mean the license header? I had updated the license year in the code base.

**Review by VishalNehra — APPROVED** [review]

**Pull request merged**
