### PR TITLE
Tried fixing dependency problem, fixed FTP button position in toolbar

### PR DESCRIPTION
**Pull request by yashwanthreddyg**

### CODE REVIEW

**Comment by vishal0071** [comment]
Thank you for your contribution.

**Comment by yashwanthreddyg** [comment]
@vishal0071 I haven't fully polish the FTPServerFragment. Please comment if there's an issure with the service or the fragment.

**Comment by vishal0071** [comment]
@yashwanthreddyg I just published a beta release over Fdroid and Play Store with your changes as I might not be able to get time to work on Amaze for some time. This will help beta testers to report any problem with your implementations and you can work on them and make pull requests.
Make sure to join our G+ community and follow xda thread.
BTW I was thinking if you could make a notification when the ftp service starts, and can have buttons in notification to stop the service. Because now you need to be in app to stop the connection, you might wanna stop connection after closing Amaze.

**Comment by yashwanthreddyg** [comment]
@vishal0071 I'll work on the notifs

**Pull request merged**
