### PR TITLE
Fix kt string casting at FileHandler

### LINKED ISSUE #2900: File handler message null value failure to typecast to kotlin.String
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux
samsung/beyond1qltesq/beyond1q:11/RP1A.200720.012/G973USQU6GUH4:user/release-keys
11 - 30
* __Device:__ beyond1q
* __Model:__ SM-G973U
* __Product:__ beyond1qltesq
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: null cannot be cast to non-null type
kotlin.String
at
com.amaze.filemanager.asynchronous.handlers.FileHandler.handleMessage(FileHandler.kt:53)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8595)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by arthur-star**
#### Issue tracker   

Fixes #2900

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
> This creates a bug: when path is null a new item is created

the switch later will decide, on line 74 it'll return without doing anything CMIIW.

**Comment by VishalNehra** [comment]
A simple null check before this line and return immediately should fix all the issues.
```
if (main.activity == null || msg == null) {
            return
        }
```

**Comment by arthur-star** [comment]
> this should probably be:
> 
> ```
> val path = msg.obj as? String
> ....
> CustomFileObserver.NEW_ITEM -> {
>     if(path == null) {
> 		Log.e(TAG, "Path is empty for file")
>         return;
>     }
> ...
> }
> ```

I changed the path to nullable string cast, and add null check.

**Comment by VishalNehra** [comment]
Can you point to hotfix/3.6.6 branch? We have plan to release it in few days.

**Comment by VishalNehra** [comment]
If you still have issues, there are not lot of changes, can you create a new branch from hotfix/3.6.6 and just copy paste your changes there.

**Pull request merged**
