### PR TITLE
Added setting to change shortcuts and disable shortcuts and quick accesses

### PR DESCRIPTION
**Pull request by EmmanuelMess**
This allows the user to change the name and path of shortcuts and create new ones. In addition quick accesses and the entire section of quick accesses and shortcuts can be (separately) disabled.
This also makes other changes:
* Making DataUtils an object that's created in MainActivity and never cleaned, can revert if this generates problems.
* Added TinyDB that let's you save entire Lists and arrays as a single String preference.
* Simplified code in Preffrag by moving all OnPreferenceClick calls to a single method.
* Added SimpleTextWatcher that implements TextWatcher and lets you override single methods.
* Added vector compatibility library to gradle files.

### CODE REVIEW

**Comment by vishal0071** [comment]
I'm sorry. What does TinyDB do again? You're saving lists in DataUtils to SharedPreferences and instead of using static access modifier for those lists we're now supposed to get them from preferences?

**Comment by EmmanuelMess** [comment]
@vishal0071 DataUtils is never saved to preferences, it has a static reference in MainActivity. TinyDB can be used to save Lists and arrays to SharedPreferences.

**Comment by vishal0071** [comment]
Then exactly which lists are you saving in preferences using TinyDB?

**Comment by vishal0071** [comment]
I'm afraid I wasn't able to start app after merging your changes.
Can you look into the issue? It crashes when I just start the app.
````
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                       at java.util.ArrayList.get(ArrayList.java:411)
                                                       at com.amaze.filemanager.fragments.TabFragment.onCreateView(TabFragment.java:116)
                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2184)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                       at com.amaze.filemanager.activities.MainActivity.onStart(MainActivity.java:1703)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                       at android.app.Activity.performStart(Activity.java:6699)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2644)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2742) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6171) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
````

**Comment by EmmanuelMess** [comment]
Check [here](https://github.com/arpitkh96/AmazeFileManager/pull/555/files#diff-60b96679770cae865677002cf13b506cR50) and [here](https://github.com/arpitkh96/AmazeFileManager/pull/555/files#diff-a17d459fc96100d4eb82abf370fd7224R69) for the data I save using TinyDB.

**Comment by EmmanuelMess** [comment]
Working on crash.

**Comment by EmmanuelMess** [comment]
It seems weird my changes would create that crash, checking the code at [TabFragment.java:116](https://github.com/arpitkh96/AmazeFileManager/pull/555/files#diff-878e98d45ea7941415a8d6458ce3d1f9R116):
`if (!dataUtils.getList().get(0).isSection()) {`
the crash would mean that dataUtils.getList() has size 0; `refreshDrawer()` it runs an AsyncTask that loads dataUtils, if it runs slower than the main thread, the app should crash like in the stack trace.

**Comment by vishal0071** [comment]
AsyncTask for refresh Drawer was long awaited, because it includes lots of database and network calls which should happen in background. Current implementation is not causing this race condition, at least not for me, this is very critical to fix. I'll also look into a solution.

**Comment by EmmanuelMess** [comment]
Race condition could happen (tested on emulator, but there are ~22ms of diference), add this to the AsyncTask:
```
                ArrayList<Boolean[]> sottyList = new ArrayList<>();
                for(int i = 0; i < 1000; i++) {
                    sottyList.add(TinyDB.getBooleanArray(sharedPref, QuickAccessPref.KEY,
                            QuickAccessPref.DEFAULT));
                }
                for(int i = 0; i < 1000; i++) {
                    Log.d("Sh code", sottyList.get(i).toString());
                }

                Log.d("Shotty code", System.currentTimeMillis() + "ms");
```
Delete data and restart, crash.

**Comment by EmmanuelMess** [comment]
As for your crash.
> Current implementation is not causing this race condition, at least not for me

I feel like an idiot, but if it's not race condition, I don't know how the items list has size 0; basically can't replicate. I'll keep trying though.

**Comment by vishal0071** [comment]
Create a new PR. I pulled your sources and tried, but couldn't reproduce it. Multi-threading needs a lot of rework so I'll start​ doing that after merging your changes.

**Comment by EmmanuelMess** [comment]
Old commits aren't listed, revert the reversion of the merge.

**Comment by vishal0071** [comment]
@EmmanuelMess the edit/delete icons you used for shortcuts, don't include their black version but while and gray instead.
Use [ThemedImageView](https://github.com/arpitkh96/AmazeFileManager/blob/master/src/main/java/com/amaze/filemanager/ui/views/ThemedImageView.java) in xml for them and app:srcDark for their dark theme resource and android:src for light theme resource

**Comment by vishal0071** [comment]
BTW really good to see you added these preferences. Thanks for your contribution (:

**Pull request merged**
