### PR TITLE
Bookmark Crashed Issue Fixed

### LINKED ISSUE #4143: [BUG] Creating a bookmark with empty directory causes error when attempting to open the bookmark
**Describe the bug**
When you create a new bookmark and leave the directory empty, if you attempt to open the bookmark afterwards you will get a message saying "Bookmark not found, recreating..." followed by a popup asking you to use a certificate installer.

**To Reproduce**
1. Got settings
2. Got to interface
3. Under the sidebar section go to bookmarks
4. Click Add Item
5. Give the bookmark a name (in my case specifically I gave the bookmark a name identical to an existing one)
6. Leave the directory blank and press create
7. Go back to the home page
8. Click on the new bookmark you created
9. See the error "Bookmark not found, recreating..."

**Expected behavior**
If a directory is invalid then this would ideally be checked at the time of creating the bookmark. The user should be prevented from creating a bookmark with an invalid directory.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S6 Lite
 - OS: Android 13
 - Rooted: No
 - Version: 3.10

### PR DESCRIPTION
**Pull request by msaqeeb72**
Bookmark Crashed Issue Fixed, added check for empty name and valid path before adding bookmark.

fixes https://github.com/TeamAmaze/AmazeFileManager/issues/4143

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishnuSanal — APPROVED** [review]
works as expected in testing, looks good to me, good to go! 🚀

**Comment by Thejas775** [comment]
@VishnuSanal is this pr waiting for some changes? or is the issue solved ?

**Comment by VishnuSanal** [comment]
> @VishnuSanal is this pr waiting for some changes? or is the issue solved ? 

It is waiting for approval/reviews from other maintainers, if they give approvals too, it'll be good to be merged.

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Thanks for your contribution. Please feel free to contact at t.me/AmazeFileManager to collect bounty for resolving this issue :)

**Pull request merged**
