### PR TITLE
Portuguese update

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by smarquespt** [comment]
@vishal0071 

Can you please build a test apk so I can check if localized strings are ok?

**Comment by vishal0071** [comment]
Here you go
https://drive.google.com/file/d/0B0u8_WTGBLT8b1g1SlVVU1MxOVE/view?usp=sharing

**Comment by smarquespt** [comment]
@vishal0071 

Thanks. It made me fix some mistakes. i´ve made a new pull request. One thing I notice is that my language and name are not in "About Amaze" -> "Translators".

Can you please add them?

**Comment by vishal0071** [comment]
Sure, I'll do..

**Pull request merged**
