### PR TITLE
Fix string comparison to actually compare

### PR DESCRIPTION
**Pull request by lbdroid**
I could have sworn that Java was one of the languages that allowed you to compare strings using the "==" operator.

### CODE REVIEW

**Comment by arpitkh96** [comment]
lol. this one always kills me

**Comment by lbdroid** [comment]
And believe it or not, I actually tested it, but apparently didn't realize that I'd changed its behavior.

**Comment by arpitkh96** [comment]
btw i need some suggestions

**Comment by lbdroid** [comment]
Certainly

**Comment by arpitkh96** [comment]
did you liked the latest fab realignment and decreased row icons size to 40dp?

**Comment by arpitkh96** [comment]
for me 40dp isnt eyes friendly but guidelines say it to be like this

**Comment by lbdroid** [comment]
The FAB does seem a bit strange. I honestly didn't even notice it until you mentioned it just now. In fact, I have a hard time making it appear -- could be my build environment.

**Comment by lbdroid** [comment]
Tell me if this is normal behavior; launch the application and the FAB is not visible. Drag the screen left and it appears at the left lower action bar. Drag the screen to the right, and it moves to the right lower action bar.

**Comment by lbdroid** [comment]
Its much smaller than the FAB in google messenger.

**Comment by lbdroid** [comment]
Hmm, that's a different type of button.

**Comment by lbdroid** [comment]
I'm getting a really weird effect on my nexus 6 that I can't reproduce on my 7 or 9. The scrollbar is crazy fat and jumpy.

**Comment by lbdroid** [comment]
The 6 is running 5.1, the other two are running 5.0.

As far as the FAB goes, if the jumping side to side thing is not a fault of my build environment, then it should be kept at the right. I'd almost be inclined to use a full size FAB at the lower right of the screen (like google messenger) in a high contrast color to stand out from the file list.

**Comment by lbdroid** [comment]
Hmm, I don't think that the guidelines are actually saying that you need to keep it down to 40dp. The first part of the guidelines appears to *accidentally* imply that a FAB at the border of the action bar should be a mini-FAB by using that as the example for a mini. If you look down lower in the guidelines, specifically starting at the heading "Placement", it shows what is clearly a standard 56dp FAB at that location.

**Comment by lbdroid** [comment]
Ah, I see that the changing sides is intentional. I would just keep it on the right, it looks too bunched up with the file list icons right there.

**Comment by arpitkh96** [comment]
Yeah some bugs are there in fab with latest changes.. Are fixable

**Comment by arpitkh96** [comment]
I don't know what scrollbar are you taking about.

**Comment by arpitkh96** [comment]
Changing sides was implemented to indicate the tab

**Comment by arpitkh96** [comment]
But I also really didn't liked the way it works now

**Comment by lbdroid** [comment]
When the file list is longer than the physical screen and you drag it up and down, the position indicator on the right of the scrollview. I'll send you a picture of what it is doing.

**Comment by arpitkh96** [comment]
The 40dp is probably used only when fab is at left top... Just to match fab size to maintain kind of consistency

**Comment by arpitkh96** [comment]
That layout of being fab just above the icons is being used a lot in examples shown in guidelines

**Comment by lbdroid** [comment]
screenshot_2015-04-10-14-55-29

(note that I'm messing around with the fab in the layout at the same time)

**Comment by lbdroid** [comment]
And to compare, this is from a nexus 7:

screenshot_2015-04-10-14-59-58

**Comment by arpitkh96** [comment]
It was expected to be 40 dp only (same as that it icons). Works fine on my moto g. And probably vishal tested this on nexus 4 too.

**Comment by arpitkh96** [comment]
Actually I don't got what you wanna show from these

**Comment by lbdroid** [comment]
On the first picture. Look at the big blocky gray line down the right edge. Its not supposed to look like that. Its supposed to look like the subtle gray line in the second image.

**Comment by arpitkh96** [comment]
Oh.... That's fast scroll bar. Just hold and drag to fast scroll. 5.1 changed its look. It's not present in you nexus 7 as list requires specific least number of items according to screen size to activate fast scroll

**Comment by lbdroid** [comment]
Ah, ok that explains it then. Actually, the Nexus 7 hasn't got 5.1 yet.

**Comment by arpitkh96** [comment]
BTW it's 1am here. Time to sleep. Ttyl

**Comment by lbdroid** [comment]
Good night!

**Pull request merged**
